// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Shopping.Server.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230114153712_UpdateProduct")]
    partial class UpdateProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shopping.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = ".NET is a free and open source framework for Windows, Linux and macOS operating systems. It is an open source successor to the .NET Framework. The project is primarily developed by Microsoft and released under the MIT License.",
                            ImageUrl = "https://dotnet.microsoft.com/blob-assets/images/e-books/blazor-for-web-forms-devs.png",
                            Price = 100m,
                            Title = "dotNet"
                        },
                        new
                        {
                            Id = 2,
                            Description = "C# is a strongly typed, multiparadigm programming language developed by Microsoft as part of the .NET platform. Its object-oriented syntax was based on C++ but includes many influences from other programming languages, such as Object Pascal and, mainly, Java.",
                            ImageUrl = "https://cdn.syncfusion.com/content/images/downloads/ebook/ebook-cover/C-sharp-Succinctly-Updated-1.png",
                            Price = 100m,
                            Title = "C#"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Blazor is a free and open source web framework that allows developers to build web apps using C# and HTML. It is being developed by Microsoft.",
                            ImageUrl = "https://cdn.syncfusion.com/content/images/downloads/ebook/ebook-cover/blazor-succinctly.png",
                            Price = 100m,
                            Title = "Blazor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
